### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icons doesn't comply by the [eOS HIG](https://elementary.io/docs/human-interface-guidelines). Pictogram should wither be extruded or inset, in this icon, I've made the icon inset in here. Let me know if you'd like some changes.

### CODE REVIEW

**Comment by arshubham** [comment]
@Fatih20 I noticed that  on icons < 64px there is a visible square background around the icon. 
Screenshot from 2019-08-15 21-40-06

**Comment by Fatih20** [comment]
Let me fix this. Didn't see this on my email.

**Comment by fitojb** [comment]
The contrast between the elements is now too low, and it looks even smudgier than it was at the small sizes.

**Comment by Fatih20** [comment]
Perhaps another round of icon redesign is needed. I'll look into it.

**Pull request merged**
